version: "3.9"
name: todos-plus-dev
services:
  backend:
    container_name: backend-dev
    image: todos-plus-backend-dev:latest
    build:
      dockerfile: Dockerfile
      context: ./apps/backend
      target: development
    volumes:
      - ./apps/backend/:/usr/src/app
    environment:
      - NODE_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=7000
      - DATABASE_URL=postgresql://todosplus:todosplus@postgres-dev:7010/todos_plus?schema=public
    command: npm run start:dev
    ports:
      - 7000:7000
    depends_on:
      - postgres
  postgres:
    container_name: postgres-dev
    image: postgres:15.4
    environment:
      POSTGRES_DB: "todos_plus"
      POSTGRES_USER: "todosplus"
      POSTGRES_PASSWORD: "todosplus"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "7010:5432"

volumes:
  postgres-data-dev: